// Language Management System for Quran Cast
class LanguageManager {
    constructor() {
        this.currentLanguage = localStorage.getItem('language') || 'ar';
        this.translations = {
            ar: {
                // Navigation
                'nav.home': 'الرئيسية',
                'nav.radio': 'الراديو',
                'nav.community': 'المجتمع',
                'nav.addPost': 'إضافة منشور',
                'nav.azkar': 'الاذكار',
                'nav.more': 'المزيد',
                
                // Sidebar
                'sidebar.appName': 'Quran Cast',
                'sidebar.login': 'تسجيل الدخول',
                'sidebar.logout': 'تسجيل الخروج',
                'sidebar.user': 'المستخدم',
                'sidebar.toggleTheme': 'تبديل الوضع',
                'sidebar.installApp': 'تثبيت التطبيق',
                'sidebar.close': 'اغلاق',
                
                // Auth Modal
                'auth.login': 'تسجيل الدخول',
                'auth.signup': 'إنشاء حساب',
                'auth.email': 'أدخل بريدك الإلكتروني',
                'auth.password': 'أدخل كلمة المرور',
                'auth.name': 'أدخل اسمك',
                'auth.confirmPassword': 'أعد إدخال كلمة المرور',
                'auth.profilePicture': 'الصورة الشخصية (اختياري)',
                'auth.profilePictureHelp': 'يمكنك اختيار صورة شخصية أو تركها فارغة لاستخدام الأيقونة الافتراضية',
                'auth.loginWithGoogle': 'تسجيل الدخول بجوجل',
                'auth.signupWithGoogle': 'إنشاء حساب بجوجل',
                'auth.noAccount': 'ليس لديك حساب؟',
                'auth.hasAccount': 'لديك حساب؟',
                'auth.registerNow': 'سجل الآن',
                'auth.loginNow': 'تسجيل الدخول',
                
                // Upload Modal
                'upload.newPost': 'منشور جديد',
                'upload.text': 'نص',
                'upload.image': 'صورة',
                'upload.video': 'فيديو',
                'upload.textContent': 'النص',
                'upload.textPlaceholder': 'اكتب منشورك هنا...',
                'upload.selectImage': 'اختر الصورة',
                'upload.selectVideo': 'اختر الفيديو',
                'upload.publish': 'نشر',
                'upload.cancel': 'إلغاء',
                
                // Footer
                'footer.description': 'تطبيق شامل للقرآن الكريم والأذكار والصلوات',
                'footer.contactUs': 'تواصل معنا',
                'footer.email': 'info@qurancast.com',
                'footer.phone': '+201111392984',
                'footer.location': 'القاهرة جمهوية مصر العربية',
                'footer.links.home': 'الرئيسية',
                'footer.links.azkar': 'الأذكار',
                'footer.links.player': 'المشغل',
                'footer.links.radio': 'الراديو',
                'footer.links.posts': 'المنشورات',
                'footer.links.prayer': 'الصلاة',
                'footer.links.qibla': 'القبلة',
                'footer.links.reading': 'القراءة',
                
                // Radio
                'radio.selectStation': 'اختر محطة إذاعية',
                'radio.fromList': 'من القائمة',
                
                // Download Page
                'download.title': 'Quran Cast',
                'download.subtitle': 'تطبيق شامل للقرآن الكريم والأذكار والصلوات',
                'download.downloadFree': 'تحميل التطبيق مجاناً',
                'download.tryNow': 'تجربة الآن',
                'download.installApp': 'تثبيت التطبيق',
                'download.installed': 'تم التثبيت',
                'download.features.backgroundPlay': 'تشغيل في الخلفية',
                'download.features.backgroundPlayDesc': 'استمع للقرآن الكريم والراديو حتى عند إغلاق التطبيق',
                'download.features.smartNotifications': 'إشعارات ذكية',
                'download.features.smartNotificationsDesc': 'تحكم كامل في التشغيل من الإشعارات',
                'download.features.mobileApp': 'تطبيق موبايل',
                'download.features.mobileAppDesc': 'يمكن تثبيته على الهاتف كتطبيق أصلي',
                'download.features.offline': 'عمل بدون إنترنت',
                'download.features.offlineDesc': 'يعمل جزئياً حتى بدون اتصال بالإنترنت',
                'download.features.islamicRadio': 'راديو إسلامي',
                'download.features.islamicRadioDesc': 'أفضل المحطات الإذاعية الإسلامية',
                'download.features.dailyAzkar': 'أذكار يومية',
                'download.features.dailyAzkarDesc': 'أذكار الصباح والمساء مع تذكيرات',
                'download.stats.stations': 'محطة إذاعية',
                'download.stats.readers': 'قارئ قرآن',
                'download.stats.azkar': 'ذكر يومي',
                'download.stats.available': 'متاح دائماً',
                'download.screenshots.title': 'شاهد التطبيق',
                'download.screenshots.subtitle': 'واجهة جميلة وسهلة الاستخدام',
                'download.screenshots.homepage': 'الصفحة الرئيسية',
                'download.screenshots.radio': 'الراديو الإسلامي',
                'download.screenshots.azkar': 'الأذكار اليومية',
                
                // Offline Page
                'offline.title': 'غير متصل بالإنترنت',
                'offline.message': 'يبدو أنك غير متصل بالإنترنت. لا تقلق، يمكنك الاستمرار في استخدام التطبيق مع الميزات المتاحة.',
                'offline.retry': 'إعادة المحاولة',
                'offline.trying': 'جاري المحاولة...',
                'offline.availableFeatures': 'الميزات المتاحة بدون إنترنت:',
                'offline.feature1': 'تصفح السور المحفوظة',
                'offline.feature2': 'تشغيل الأذكار المحفوظة',
                'offline.feature3': 'الوصول للصفحات المحفوظة',
                'offline.feature4': 'إعدادات التطبيق',
                
                // Common
                'common.close': 'إغلاق',
                'common.cancel': 'إلغاء',
                'common.save': 'حفظ',
                'common.delete': 'حذف',
                'common.edit': 'تعديل',
                'common.loading': 'جاري التحميل...',
                'common.error': 'حدث خطأ',
                'common.success': 'تم بنجاح',
                'common.retry': 'إعادة المحاولة',
                'common.yes': 'نعم',
                'common.no': 'لا',
                'common.ok': 'موافق',
                'common.add': 'إضافة',
                'common.language': 'English',
                
                // Prayer Times
                'prayer.fajr': 'الفجر',
                'prayer.dhuhr': 'الظهر',
                'prayer.asr': 'العصر',
                'prayer.maghrib': 'المغرب',
                'prayer.isha': 'العشاء',
                'prayer.sunrise': 'الشروق',
                'prayer.nextPrayer': 'الصلاة القادمة',
                'prayer.timeRemaining': 'الوقت المتبقي',
                'prayer.location': 'الموقع',
                'prayer.date': 'التاريخ',
                'prayer.qibla': 'القبلة',
                'prayer.qiblaDirection': 'اتجاه القبلة',
                'prayer.distance': 'المسافة إلى مكة',
                'prayer.km': 'كم',
                'prayer.degrees': 'درجة',
                'prayer.north': 'شمال',
                'prayer.northeast': 'شمال شرق',
                'prayer.east': 'شرق',
                'prayer.southeast': 'جنوب شرق',
                'prayer.south': 'جنوب',
                'prayer.southwest': 'جنوب غرب',
                'prayer.west': 'غرب',
                'prayer.northwest': 'شمال غرب',
                'prayer.todayTimes': 'مواقيت الصلاة اليوم',
                'prayer.passed': 'مرت',
                'prayer.upcoming': 'قادمة',
                'prayer.current': 'حالية',
                'prayer.now': 'الآن',
                'prayer.ended': 'مضت',
                
                // Azkar Categories
                'azkar.morningEvening': 'أذكار الصباح والمساء',
                'azkar.sleeping': 'أذكار النوم',
                'azkar.waking': 'أذكار الاستيقاظ',
                'azkar.eating': 'أذكار الطعام',
                'azkar.traveling': 'أذكار السفر',
                'azkar.rain': 'أذكار المطر',
                'azkar.wind': 'أذكار الرياح',
                'azkar.thunder': 'أذكار الرعد',
                'azkar.afterPrayer': 'أذكار بعد الصلاة',
                'azkar.remembrance': 'الأذكار',
                'azkar.tasbih': 'التسبيح',
                'azkar.count': 'العدد',
                'azkar.reset': 'إعادة تعيين',
                'azkar.play': 'تشغيل',
                'azkar.pause': 'إيقاف',
                'azkar.stop': 'توقف',
                'azkar.description': 'اذكر الله في كل وقت وكل مكان، واجعل ذكر الله نوراً في قلبك',
                'azkar.searchPlaceholder': 'ابحث عن فئة الأذكار...',
                'azkar.prayerRemembrance': 'اذكار الصلاة',
                'azkar.customize': 'تخصيص',
                'azkar.selectDhikr': 'اختر ذكراً للبدء',
                'azkar.addCustomDhikr': 'إضافة ذكر مخصص',
                'azkar.dhikrText': 'نص الذكر',
                'azkar.dhikrExample': 'مثال: لا حول ولا قوة إلا بالله',
                'azkar.repeatCount': 'عدد مرات التكرار',
                'azkar.countExample': 'مثال: 99',
                'azkar.sleeping': 'أذكار النوم',
                'azkar.waking': 'أذكار الاستيقاظ من النوم',
                'azkar.toiletEnter': 'دعاء دخول الخلاء',
                'azkar.toiletExit': 'دعاء الخروج من الخلاء',
                'azkar.beforeWudu': 'الذكر قبل الوضوء',
                'azkar.afterWudu': 'الذكر بعد الفراغ من الوضوء',
                'azkar.leavingHome': 'الذكر عند الخروج من المنزل',
                'azkar.enteringHome': 'الذكر عند دخول المنزل',
                'azkar.goingToMosque': 'دعاء الذهاب إلى المسجد',
                'azkar.enteringMosque': 'دعاء دخول المسجد',
                'azkar.leavingMosque': 'دعاء الخروج من المسجد',
                'azkar.adhan': 'أذكار الآذان',
                'azkar.wearingClothes': 'دعاء لبس الثوب',
                'azkar.wearingNewClothes': 'دعاء لبس الثوب الجديد',
                'azkar.blessingNewClothes': 'الدعاء لمن لبس ثوبا جديدا',
                'azkar.removingClothes': 'ما يقول إذا وضع ثوبه',
                'azkar.openingPrayer': 'دعاء الاستفتاح',
                'azkar.ruku': 'دعاء الركوع',
                'azkar.risingFromRuku': 'دعاء الرفع من الركوع',
                'azkar.sujood': 'دعاء السجود',
                'azkar.sittingBetweenSujood': 'دعاء الجلسة بين السجدتين',
                'azkar.sujoodTilawah': 'دعاء سجود التلاوة',
                'azkar.tashahhud': 'التشهد',
                'azkar.sendingBlessings': 'الصلاة على النبي بعد التشهد',
                'azkar.finalSupplication': 'الدعاء بعد التشهد الأخير قبل السلام',
                'azkar.afterPrayer': 'الأذكار بعد السلام من الصلاة',
                'azkar.istikharah': 'دعاء صلاة الاستخارة',
                'azkar.nightTurning': 'الدعاء إذا تقلب ليلا',
                'azkar.nightmare': 'دعاء الفزع في النوم و من بُلِيَ بالوحشة',
                'azkar.dreams': 'ما يفعل من رأى الرؤيا أو الحلم',
                'azkar.witrQunoot': 'دعاء قنوت الوتر',
                'azkar.afterWitr': 'الذكر عقب السلام من الوتر',
                'azkar.sadness': 'دعاء الهم والحزن',
                'azkar.distress': 'دعاء الكرب',
                'azkar.enemyMeeting': 'دعاء لقاء العدو و ذي السلطان',
                'azkar.oppressionFear': 'دعاء من خاف ظلم السلطان',
                'azkar.againstEnemy': 'الدعاء على العدو',
                'azkar.peopleFear': 'ما يقول من خاف قوما',
                'azkar.faithDoubt': 'دعاء من أصابه وسوسة في الإيمان',
                'azkar.debtRepayment': 'دعاء قضاء الدين',
                'azkar.prayerWhisper': 'دعاء الوسوسة في الصلاة و القراءة',
                'azkar.difficultMatter': 'دعاء من استصعب عليه أمر',
                'azkar.sinCommitted': 'ما يقول ويفعل من أذنب ذنبا',
                'azkar.satanRepellent': 'دعاء طرد الشيطان و وساوسه',
                'azkar.unwantedEvent': 'الدعاء حينما يقع ما لا يرضاه أو غلب على أمره',
                'azkar.newbornCongratulation': 'تهنئة المولود له وجوابه',
                'azkar.childrenProtection': 'ما يعوذ به الأولاد',
                'azkar.visitingSick': 'الدعاء للمريض في عيادته',
                'azkar.visitingSickVirtue': 'فضل عيادة المريض',
                'azkar.dyingPerson': 'دعاء المريض الذي يئس من حياته',
                'azkar.deathbed': 'تلقين المحتضر',
                'azkar.calamity': 'دعاء من أصيب بمصيبة',
                'azkar.closingEyes': 'الدعاء عند إغماض الميت',
                'azkar.deadPersonPrayer': 'الدعاء للميت في الصلاة عليه',
                'azkar.childPrayer': 'الدعاء للفرط في الصلاة عليه',
                'azkar.condolence': 'دعاء التعزية',
                'azkar.burial': 'الدعاء عند إدخال الميت القبر',
                'azkar.afterBurial': 'الدعاء بعد دفن الميت',
                'azkar.graveVisiting': 'دعاء زيارة القبور',
                'azkar.wind': 'دعاء الريح',
                'azkar.thunder': 'دعاء الرعد',
                'azkar.rainRequest': 'من أدعية الاستسقاء',
                'azkar.rainFalling': 'الدعاء إذا نزل المطر',
                'azkar.afterRain': 'الذكر بعد نزول المطر',
                'azkar.sunshineRequest': 'من أدعية الاستصحاء',
                'azkar.newMoon': 'دعاء رؤية الهلال',
                'azkar.breakingFast': 'الدعاء عند إفطار الصائم',
                'azkar.beforeEating': 'الدعاء قبل الطعام',
                'azkar.afterEating': 'الدعاء عند الفراغ من الطعام',
                'azkar.guestBlessing': 'دعاء الضيف لصاحب الطعام',
                'azkar.foodRequest': 'التعريض بالدعاء لطلب الطعام أو الشراب',
                'azkar.guestBreakingFast': 'الدعاء إذا أفطر عند أهل بيت',
                'azkar.fastingPerson': 'دعاء الصائم إذا حضر الطعام ولم يفطر',
                'azkar.fastingInsult': 'ما يقول الصائم إذا سابه أحد',
                'azkar.firstFruit': 'الدعاء عند رؤية باكورة الثمر',
                'azkar.sneezing': 'دعاء العطاس',
                'azkar.kafirSneezing': 'ما يقال للكافر إذا عطس فحمد الله',
                'azkar.marriage': 'الدعاء للمتزوج',
                'azkar.marriageAndAnimal': 'دعاء المتزوج و شراء الدابة',
                'azkar.beforeIntimacy': 'الدعاء قبل إتيان الزوجة',
                'azkar.anger': 'دعاء الغضب',
                'azkar.afflictedPerson': 'دعاء من رأى مبتلى',
                'azkar.gathering': 'ما يقال في المجلس',
                'azkar.gatheringExpiation': 'كفارة المجلس',
                'azkar.forgivenessRequest': 'الدعاء لمن قال غفر الله لك',
                'azkar.kindness': 'الدعاء لمن صنع إليك معروفا',
                'azkar.dajjalProtection': 'ما يعصم الله به من الدجال',
                'azkar.loveInAllah': 'الدعاء لمن قال إني أحبك في الله',
                'azkar.wealthOffer': 'الدعاء لمن عرض عليك ماله',
                'azkar.loanRepayment': 'الدعاء لمن أقرض عند القضاء',
                'azkar.shirkFear': 'دعاء الخوف من الشرك',
                'azkar.blessingResponse': 'الدعاء لمن قال بارك الله فيك',
                'azkar.badOmen': 'دعاء كراهية الطيرة',
                'azkar.riding': 'دعاء الركوب',
                'azkar.travel': 'دعاء السفر',
                'azkar.enteringVillage': 'دعاء دخول القرية أو البلدة',
                'azkar.enteringMarket': 'دعاء دخول السوق',
                'azkar.vehicleTrouble': 'الدعاء إذا تعس المركوب',
                'azkar.travelerForResident': 'دعاء المسافر للمقيم',
                'azkar.residentForTraveler': 'دعاء المقيم للمسافر',
                'azkar.travelTasbih': 'التكبير و التسبيح في سير السفر',
                'azkar.travelerDawn': 'دعاء المسافر إذا أسحر',
                'azkar.travelStop': 'الدعاء إذا نزل مترلا في سفر أو غيره',
                'azkar.returningFromTravel': 'ذكر الرجوع من السفر',
                'azkar.goodOrBadNews': 'ما يقول من أتاه أمر يسره أو يكرهه',
                'azkar.blessingProphet': 'فضل الصلاة على النبي صلى الله عليه و سلم',
                'azkar.spreadingSalam': 'إفشاء السلام',
                'azkar.kafirSalam': 'كيف يرد السلام على الكافر إذا سلم',
                'azkar.roosterCrow': 'الدُّعاءُ عِنْدَ سَمَاعِ صِياحِ الدِّيكِ ونَهِيقِ الْحِمَارِ',
                'azkar.dogBark': 'دعاء نباح الكلاب بالليل',
                'azkar.insulted': 'الدعاء لمن سببته',
                'azkar.praise': 'ما يقول المسلم إذا مدح المسلم',
                'azkar.compliment': 'ما يقول المسلم إذا زكي',
                'azkar.hajjTalbiyah': 'كيف يلبي المحرم في الحج أو العمرة ؟',
                'azkar.blackStoneTakbir': 'التكبير إذا أتى الركن الأسود',
                'azkar.yamaniCorner': 'الدعاء بين الركن اليماني والحجر الأسود',
                'azkar.safaMarwa': 'دعاء الوقوف على الصفا والمروة',
                'azkar.arafatDay': 'الدعاء يوم عرفة',
                'azkar.masharHaram': 'الذكر عند المشعر الحرام',
                'azkar.stoneThrowing': 'التكبير عند رمي الجمار مع كل حصاة',
                'azkar.amazement': 'دعاء التعجب والأمر السار',
                'azkar.goodNews': 'ما يفعل من أتاه أمر يسره',
                'azkar.bodyPain': 'ما يقول من أحس وجعا في جسده',
                'azkar.evilEye': 'دعاء من خشي أن يصيب شيئا بعينه',
                'azkar.fright': 'ما يقال عند الفزع',
                'azkar.slaughtering': 'ما يقول عند الذبح أو النحر',
                'azkar.satanRepellent2': 'ما يقول لرد كيد مردة الشياطين',
                'azkar.repentance': 'الاستغفار و التوبة',
                'azkar.tasbihVirtue': 'فضل التسبيح و التحميد، و التهليل، و التكبير',
                'azkar.prophetTasbih': 'كيف كان النبي يسبح؟',
                'azkar.goodDeeds': 'من أنواع الخير والآداب الجامعة',
                'azkar.dhikrAdded': 'تم إضافة الذكر: {text} ({count} مرة)',
                'azkar.dhikrCompleted': 'تم إكمال الذكر: {text}!',
                'azkar.dhikrLinked': 'تم ربط الذكر: {text} مع السبحة',
                'azkar.counterReset': 'تم إعادة تعيين العداد',
                'azkar.dhikrLinkedWithTasbih': 'تم ربط الذكر مع المسبحة',
                
                // Radio Stations
                'radio.egyptQuran': 'إذاعة القرآن الكريم – القاهرة',
                'radio.tarateel': 'تراتيل',
                'radio.tlawat': 'تلاوات خاشعة',
                'radio.tafsir': 'تفسير',
                'radio.sira': 'المختصر في السيرة النبوية',
                'radio.siraShadows': 'في ظلال السيرة النبوية',
                'radio.sahaba': 'صور من حياة الصحابة',
                'radio.abdulbasitMoratal': 'إذاعة الشيخ عبدالباسط عبدالصمد – تلاوات خالدة',
                'radio.abdulbasitMojawwad': 'إذاعة الشيخ عبدالباسط عبدالصمد',
                'radio.selectStation': 'اختر محطة إذاعية',
                'radio.fromList': 'من القائمة',
                'radio.nowPlaying': 'جاري التشغيل',
                'radio.volume': 'الصوت',
                'radio.mute': 'كتم الصوت',
                'radio.unmute': 'إلغاء كتم الصوت',
                'radio.stop': 'إيقاف',
                'radio.play': 'تشغيل',
                'radio.pause': 'إيقاف مؤقت',
                'radio.loading': 'جاري التحميل...',
                'radio.error': 'خطأ في التشغيل',
                'radio.retry': 'إعادة المحاولة',
                'radio.description': 'استمع إلى أفضل الإذاعات الإسلامية من مختلف الدول العربية',
                
                // Quran Readers
                'reader.alafasy': 'مشاري العفاسي',
                'reader.yasseraldossari': 'ياسر الدوسري',
                'reader.abdulbasitmurattal': 'عبد الباسط عبد الصمد (مرتل)',
                'reader.abdulbasitmujawwad': 'عبد الباسط عبد الصمد (مجود)',
                'reader.ahmedalajmi': 'احمد العجمي',
                'reader.muhammadayyub': 'محمد أيوب',
                'reader.abdulazizazzahrani': 'عبد العزيز الزهراني',
                'reader.muhammadsiddiqalminshawimujawwad': 'محمد صديق المنشاوي (مجود)',
                'reader.mustafaismail': 'مصطفي اسماعيل',
                'reader.abdullahalmatrood': 'عبد الله المطرود',
                'reader.abdullahawadaljuhani': 'عبد الله عواد الجهني',
                'reader.abdullahbasfar': 'عبد الله بصفر',
                'reader.abdullahkhayat': 'عبد الله خياط',
                'reader.abdullahkhulaifi': 'عبد الله خليفي',
                'reader.abdulmohsenalharthy': 'عبد المحسن الحارثي',
                'reader.abdulmuhsinalqasim': 'عبد المحسن القاسم',
                'reader.abdulmunimabdulmubdi': 'عبد المنعم عبد المبدي',
                'reader.abdulwadoodhaneef': 'عبد الودود حنيف',
                'reader.abdurrasheedsufiabialhaarithanalkasaaee': 'عبد الرشيد الصوفي [أبي الحارث عن الكسائي]',
                'reader.abdurrasheedsufiaddoorianabiamr': 'عبد الرشيد الصوفي [الدوري عن أبي عمرو]',
                'reader.abdurrasheedsufishubahanasim': 'عبد الرشيد الصوفي [شعبة عن عاصم]',
                'reader.abdurrasheedsufisoosi': 'عبد الرشيد الصوفي [السوسي]',
                'reader.abdurrazaqbinabtanaldulaimi': 'عبد الرزاق بن أبتان الدليمي',
                'reader.abuabdullahmuniraltounsi': 'أبو عبد الله منير التونسي',
                'reader.abubakraldhabi': 'أبو بكر الذهبي',
                'reader.adilkalbani': 'عادل كالبياني',
                'reader.ahmadalhawashy': 'أحمد الحواشي',
                'reader.ahmadalnufais': 'أحمد النفيس',
                'reader.ahmadkhaderaltarabulsi': 'أحمد خضر الطرابلسي',
                'reader.ahmadsulaiman': 'أحمد سليمان',
                'reader.ahmedalhammad': 'أحمد الحماد',
                'reader.ahmedalmisbahi': 'أحمد المصباحي',
                'reader.ahmedamir': 'أحمد أمير',
                'reader.ahmedmohamedsalama': 'أحمد محمد سلامة',
                'reader.ahmedsaber': 'أحمد صابر',
                'reader.alashryomran': 'الأشري عمران',
                
                // Player
                'player.showMoreReaders': 'عرض المزيد من القراء',
                'player.selectReader': 'اختر القارئ',
                'player.searchReader': 'ابحث عن قارئ...',
                
                // Surah Names
                'surah.al-fatihah': 'سورة الفاتحة',
                'surah.al-baqarah': 'سورة البقرة',
                'surah.ali-imran': 'سورة آل عمران',
                'surah.an-nisa': 'سورة النساء',
                'surah.al-maidah': 'سورة المائدة',
                'surah.al-anam': 'سورة الأنعام',
                'surah.al-araf': 'سورة الأعراف',
                'surah.al-anfal': 'سورة الأنفال',
                'surah.at-tawbah': 'سورة التوبة',
                'surah.yunus': 'سورة يونس',
                'surah.hud': 'سورة هود',
                'surah.yusuf': 'سورة يوسف',
                'surah.ar-rad': 'سورة الرعد',
                'surah.ibrahim': 'سورة إبراهيم',
                'surah.al-hijr': 'سورة الحجر',
                'surah.an-nahl': 'سورة النحل',
                'surah.al-isra': 'سورة الإسراء',
                'surah.al-kahf': 'سورة الكهف',
                'surah.maryam': 'سورة مريم',
                'surah.taha': 'سورة طه',
                'surah.al-anbiya': 'سورة الأنبياء',
                'surah.al-hajj': 'سورة الحج',
                'surah.al-muminun': 'سورة المؤمنون',
                'surah.an-nur': 'سورة النور',
                'surah.al-furqan': 'سورة الفرقان',
                'surah.ash-shuara': 'سورة الشعراء',
                'surah.an-naml': 'سورة النمل',
                'surah.al-qasas': 'سورة القصص',
                'surah.al-ankabut': 'سورة العنكبوت',
                'surah.ar-rum': 'سورة الروم',
                'surah.luqman': 'سورة لقمان',
                'surah.as-sajdah': 'سورة السجدة',
                'surah.al-ahzab': 'سورة الأحزاب',
                'surah.saba': 'سورة سبأ',
                'surah.fatir': 'سورة فاطر',
                'surah.ya-sin': 'سورة يس',
                'surah.as-saffat': 'سورة الصافات',
                'surah.sad': 'سورة ص',
                'surah.az-zumar': 'سورة الزمر',
                'surah.ghafir': 'سورة غافر',
                'surah.fussilat': 'سورة فصلت',
                'surah.ash-shura': 'سورة الشورى',
                'surah.az-zukhruf': 'سورة الزخرف',
                'surah.ad-dukhan': 'سورة الدخان',
                'surah.al-jathiyah': 'سورة الجاثية',
                'surah.al-ahqaf': 'سورة الأحقاف',
                'surah.muhammad': 'سورة محمد',
                'surah.al-fath': 'سورة الفتح',
                'surah.al-hujurat': 'سورة الحجرات',
                'surah.qaf': 'سورة ق',
                'surah.adh-dhariyat': 'سورة الذاريات',
                'surah.at-tur': 'سورة الطور',
                'surah.an-najm': 'سورة النجم',
                'surah.al-qamar': 'سورة القمر',
                'surah.ar-rahman': 'سورة الرحمن',
                'surah.al-waqiah': 'سورة الواقعة',
                'surah.al-hadid': 'سورة الحديد',
                'surah.al-mujadila': 'سورة المجادلة',
                'surah.al-hashr': 'سورة الحشر',
                'surah.al-mumtahanah': 'سورة الممتحنة',
                'surah.as-saff': 'سورة الصف',
                'surah.al-jumuah': 'سورة الجمعة',
                'surah.al-munafiqun': 'سورة المنافقون',
                'surah.at-taghabun': 'سورة التغابن',
                'surah.at-talaq': 'سورة الطلاق',
                'surah.at-tahrim': 'سورة التحريم',
                'surah.al-mulk': 'سورة الملك',
                'surah.al-qalam': 'سورة القلم',
                'surah.al-haqqah': 'سورة الحاقة',
                'surah.al-maarij': 'سورة المعارج',
                'surah.nuh': 'سورة نوح',
                'surah.al-jinn': 'سورة الجن',
                'surah.al-muzzammil': 'سورة المزمل',
                'surah.al-muddaththir': 'سورة المدثر',
                'surah.al-qiyamah': 'سورة القيامة',
                'surah.al-insan': 'سورة الإنسان',
                'surah.al-mursalat': 'سورة المرسلات',
                'surah.an-naba': 'سورة النبأ',
                'surah.an-naziat': 'سورة النازعات',
                'surah.abasa': 'سورة عبس',
                'surah.at-takwir': 'سورة التكوير',
                'surah.al-infitar': 'سورة الانفطار',
                'surah.al-mutaffifin': 'سورة المطففين',
                'surah.al-inshiqaq': 'سورة الانشقاق',
                'surah.al-buruj': 'سورة البروج',
                'surah.at-tariq': 'سورة الطارق',
                'surah.al-ala': 'سورة الأعلى',
                'surah.al-ghashiyah': 'سورة الغاشية',
                'surah.al-fajr': 'سورة الفجر',
                'surah.al-balad': 'سورة البلد',
                'surah.ash-shams': 'سورة الشمس',
                'surah.al-layl': 'سورة الليل',
                'surah.ad-duha': 'سورة الضحى',
                'surah.ash-sharh': 'سورة الشرح',
                'surah.at-tin': 'سورة التين',
                'surah.al-alaq': 'سورة العلق',
                'surah.al-qadr': 'سورة القدر',
                'surah.al-bayyinah': 'سورة البينة',
                'surah.az-zalzalah': 'سورة الزلزلة',
                'surah.al-adiyat': 'سورة العاديات',
                'surah.al-qariah': 'سورة القارعة',
                'surah.at-takathur': 'سورة التكاثر',
                'surah.al-asr': 'سورة العصر',
                'surah.al-humazah': 'سورة الهمزة',
                'surah.al-fil': 'سورة الفيل',
                'surah.quraysh': 'سورة قريش',
                'surah.al-maun': 'سورة الماعون',
                'surah.al-kawthar': 'سورة الكوثر',
                'surah.al-kafirun': 'سورة الكافرون',
                'surah.an-nasr': 'سورة النصر',
                'surah.al-masad': 'سورة المسد',
                'surah.al-ikhlas': 'سورة الإخلاص',
                'surah.al-falaq': 'سورة الفلق',
                'surah.an-nas': 'سورة الناس'
            },
            en: {
                // Navigation
                'nav.home': 'Home',
                'nav.radio': 'Radio',
                'nav.community': 'Community',
                'nav.addPost': 'Add Post',
                'nav.azkar': 'Azkar',
                'nav.more': 'More',
                
                // Sidebar
                'sidebar.appName': 'Quran Cast',
                'sidebar.login': 'Login',
                'sidebar.logout': 'Logout',
                'sidebar.user': 'User',
                'sidebar.toggleTheme': 'Toggle Theme',
                'sidebar.installApp': 'Install App',
                'sidebar.close': 'Close',
                
                // Auth Modal
                'auth.login': 'Login',
                'auth.signup': 'Sign Up',
                'auth.email': 'Enter your email',
                'auth.password': 'Enter your password',
                'auth.name': 'Enter your name',
                'auth.confirmPassword': 'Confirm password',
                'auth.profilePicture': 'Profile Picture (Optional)',
                'auth.profilePictureHelp': 'You can choose a profile picture or leave it empty to use the default icon',
                'auth.loginWithGoogle': 'Login with Google',
                'auth.signupWithGoogle': 'Sign up with Google',
                'auth.noAccount': "Don't have an account?",
                'auth.hasAccount': 'Have an account?',
                'auth.registerNow': 'Register now',
                'auth.loginNow': 'Login',
                
                // Upload Modal
                'upload.newPost': 'New Post',
                'upload.text': 'Text',
                'upload.image': 'Image',
                'upload.video': 'Video',
                'upload.textContent': 'Text',
                'upload.textPlaceholder': 'Write your post here...',
                'upload.selectImage': 'Select Image',
                'upload.selectVideo': 'Select Video',
                'upload.publish': 'Publish',
                'upload.cancel': 'Cancel',
                
                // Footer
                'footer.description': 'Comprehensive app for Quran, Azkar and Prayers',
                'footer.contactUs': 'Contact Us',
                'footer.email': 'info@qurancast.com',
                'footer.phone': '+201111392984',
                'footer.location': 'Cairo, Arab Republic of Egypt',
                'footer.links.home': 'Home',
                'footer.links.azkar': 'Azkar',
                'footer.links.player': 'Player',
                'footer.links.radio': 'Radio',
                'footer.links.posts': 'Posts',
                'footer.links.prayer': 'Prayer',
                'footer.links.qibla': 'Qibla',
                'footer.links.reading': 'Reading',
                
                // Radio
                'radio.selectStation': 'Select Radio Station',
                'radio.fromList': 'From List',
                
                // Download Page
                'download.title': 'Quran Cast',
                'download.subtitle': 'Comprehensive app for Quran, Azkar and Prayers',
                'download.downloadFree': 'Download App Free',
                'download.tryNow': 'Try Now',
                'download.installApp': 'Install App',
                'download.installed': 'Installed',
                'download.features.backgroundPlay': 'Background Play',
                'download.features.backgroundPlayDesc': 'Listen to Quran and radio even when the app is closed',
                'download.features.smartNotifications': 'Smart Notifications',
                'download.features.smartNotificationsDesc': 'Full control over playback from notifications',
                'download.features.mobileApp': 'Mobile App',
                'download.features.mobileAppDesc': 'Can be installed on phone as a native app',
                'download.features.offline': 'Offline Mode',
                'download.features.offlineDesc': 'Works partially even without internet connection',
                'download.features.islamicRadio': 'Islamic Radio',
                'download.features.islamicRadioDesc': 'Best Islamic radio stations',
                'download.features.dailyAzkar': 'Daily Azkar',
                'download.features.dailyAzkarDesc': 'Morning and evening Azkar with reminders',
                'download.stats.stations': 'Radio Stations',
                'download.stats.readers': 'Quran Readers',
                'download.stats.azkar': 'Daily Azkar',
                'download.stats.available': 'Available 24/7',
                'download.screenshots.title': 'See the App',
                'download.screenshots.subtitle': 'Beautiful and easy to use interface',
                'download.screenshots.homepage': 'Homepage',
                'download.screenshots.radio': 'Islamic Radio',
                'download.screenshots.azkar': 'Daily Azkar',
                
                // Offline Page
                'offline.title': 'Offline',
                'offline.message': 'It seems you are not connected to the internet. Don\'t worry, you can continue using the app with available features.',
                'offline.retry': 'Retry',
                'offline.trying': 'Trying...',
                'offline.availableFeatures': 'Available features offline:',
                'offline.feature1': 'Browse saved Surahs',
                'offline.feature2': 'Play saved Azkar',
                'offline.feature3': 'Access saved pages',
                'offline.feature4': 'App settings',
                
                // Common
                'common.close': 'Close',
                'common.cancel': 'Cancel',
                'common.save': 'Save',
                'common.delete': 'Delete',
                'common.edit': 'Edit',
                'common.loading': 'Loading...',
                'common.error': 'An error occurred',
                'common.success': 'Success',
                'common.retry': 'Retry',
                'common.yes': 'Yes',
                'common.no': 'No',
                'common.ok': 'OK',
                'common.add': 'Add',
                'common.language': 'العربية',
                
                // Prayer Times
                'prayer.fajr': 'Fajr',
                'prayer.dhuhr': 'Dhuhr',
                'prayer.asr': 'Asr',
                'prayer.maghrib': 'Maghrib',
                'prayer.isha': 'Isha',
                'prayer.sunrise': 'Sunrise',
                'prayer.nextPrayer': 'Next Prayer',
                'prayer.timeRemaining': 'Time Remaining',
                'prayer.location': 'Location',
                'prayer.date': 'Date',
                'prayer.qibla': 'Qibla',
                'prayer.qiblaDirection': 'Qibla Direction',
                'prayer.distance': 'Distance to Makkah',
                'prayer.km': 'km',
                'prayer.degrees': 'degrees',
                'prayer.north': 'North',
                'prayer.northeast': 'Northeast',
                'prayer.east': 'East',
                'prayer.southeast': 'Southeast',
                'prayer.south': 'South',
                'prayer.southwest': 'Southwest',
                'prayer.west': 'West',
                'prayer.northwest': 'Northwest',
                'prayer.todayTimes': 'Today\'s Prayer Times',
                'prayer.passed': 'Passed',
                'prayer.upcoming': 'Upcoming',
                'prayer.current': 'Current',
                'prayer.now': 'Now',
                'prayer.ended': 'Ended',
                
                // Azkar Categories
                'azkar.morningEvening': 'Morning & Evening Remembrance',
                'azkar.sleeping': 'Sleep Remembrance',
                'azkar.waking': 'Waking Remembrance',
                'azkar.eating': 'Eating Remembrance',
                'azkar.traveling': 'Travel Remembrance',
                'azkar.rain': 'Rain Remembrance',
                'azkar.wind': 'Wind Remembrance',
                'azkar.thunder': 'Thunder Remembrance',
                'azkar.afterPrayer': 'After Prayer Remembrance',
                'azkar.remembrance': 'Remembrance',
                'azkar.tasbih': 'Tasbih',
                'azkar.count': 'Count',
                'azkar.reset': 'Reset',
                'azkar.play': 'Play',
                'azkar.pause': 'Pause',
                'azkar.stop': 'Stop',
                'azkar.description': 'Remember Allah at all times and in all places, and make the remembrance of Allah a light in your heart',
                'azkar.searchPlaceholder': 'Search for remembrance category...',
                'azkar.prayerRemembrance': 'Prayer Remembrance',
                'azkar.customize': 'Customize',
                'azkar.selectDhikr': 'Select a remembrance to start',
                'azkar.addCustomDhikr': 'Add Custom Remembrance',
                'azkar.dhikrText': 'Remembrance Text',
                'azkar.dhikrExample': 'Example: La hawla wa la quwwata illa billah',
                'azkar.repeatCount': 'Repeat Count',
                'azkar.countExample': 'Example: 99',
                'azkar.sleeping': 'Sleep Remembrance',
                'azkar.waking': 'Waking from Sleep Remembrance',
                'azkar.toiletEnter': 'Toilet Entry Supplication',
                'azkar.toiletExit': 'Toilet Exit Supplication',
                'azkar.beforeWudu': 'Remembrance Before Wudu',
                'azkar.afterWudu': 'Remembrance After Wudu',
                'azkar.leavingHome': 'Remembrance When Leaving Home',
                'azkar.enteringHome': 'Remembrance When Entering Home',
                'azkar.goingToMosque': 'Going to Mosque Supplication',
                'azkar.enteringMosque': 'Entering Mosque Supplication',
                'azkar.leavingMosque': 'Leaving Mosque Supplication',
                'azkar.adhan': 'Adhan Remembrance',
                'azkar.wearingClothes': 'Wearing Clothes Supplication',
                'azkar.wearingNewClothes': 'Wearing New Clothes Supplication',
                'azkar.blessingNewClothes': 'Blessing for New Clothes',
                'azkar.removingClothes': 'What to Say When Removing Clothes',
                'azkar.openingPrayer': 'Opening Prayer Supplication',
                'azkar.ruku': 'Ruku Supplication',
                'azkar.risingFromRuku': 'Rising from Ruku Supplication',
                'azkar.sujood': 'Sujood Supplication',
                'azkar.sittingBetweenSujood': 'Sitting Between Sujood Supplication',
                'azkar.sujoodTilawah': 'Sujood Tilawah Supplication',
                'azkar.tashahhud': 'Tashahhud',
                'azkar.sendingBlessings': 'Sending Blessings on Prophet',
                'azkar.finalSupplication': 'Final Supplication Before Salam',
                'azkar.afterPrayer': 'Remembrance After Prayer',
                'azkar.istikharah': 'Istikharah Supplication',
                'azkar.nightTurning': 'Supplication When Turning at Night',
                'azkar.nightmare': 'Nightmare and Fear Supplication',
                'azkar.dreams': 'What to Do When Seeing Dreams',
                'azkar.witrQunoot': 'Witr Qunoot Supplication',
                'azkar.afterWitr': 'Remembrance After Witr',
                'azkar.sadness': 'Sadness and Grief Supplication',
                'azkar.distress': 'Distress Supplication',
                'azkar.enemyMeeting': 'Enemy and Authority Meeting Supplication',
                'azkar.oppressionFear': 'Oppression Fear Supplication',
                'azkar.againstEnemy': 'Supplication Against Enemy',
                'azkar.peopleFear': 'What to Say When Fearing People',
                'azkar.faithDoubt': 'Faith Doubt Supplication',
                'azkar.debtRepayment': 'Debt Repayment Supplication',
                'azkar.prayerWhisper': 'Prayer Whisper Supplication',
                'azkar.difficultMatter': 'Difficult Matter Supplication',
                'azkar.sinCommitted': 'What to Say When Committing Sin',
                'azkar.satanRepellent': 'Satan Repellent Supplication',
                'azkar.unwantedEvent': 'Unwanted Event Supplication',
                'azkar.newbornCongratulation': 'Newborn Congratulation',
                'azkar.childrenProtection': 'Children Protection',
                'azkar.visitingSick': 'Visiting Sick Supplication',
                'azkar.visitingSickVirtue': 'Visiting Sick Virtue',
                'azkar.dyingPerson': 'Dying Person Supplication',
                'azkar.deathbed': 'Deathbed Guidance',
                'azkar.calamity': 'Calamity Supplication',
                'azkar.closingEyes': 'Closing Eyes Supplication',
                'azkar.deadPersonPrayer': 'Dead Person Prayer Supplication',
                'azkar.childPrayer': 'Child Prayer Supplication',
                'azkar.condolence': 'Condolence Supplication',
                'azkar.burial': 'Burial Supplication',
                'azkar.afterBurial': 'After Burial Supplication',
                'azkar.graveVisiting': 'Grave Visiting Supplication',
                'azkar.wind': 'Wind Supplication',
                'azkar.thunder': 'Thunder Supplication',
                'azkar.rainRequest': 'Rain Request Supplications',
                'azkar.rainFalling': 'Rain Falling Supplication',
                'azkar.afterRain': 'After Rain Remembrance',
                'azkar.sunshineRequest': 'Sunshine Request Supplications',
                'azkar.newMoon': 'New Moon Supplication',
                'azkar.breakingFast': 'Breaking Fast Supplication',
                'azkar.beforeEating': 'Before Eating Supplication',
                'azkar.afterEating': 'After Eating Supplication',
                'azkar.guestBlessing': 'Guest Blessing Supplication',
                'azkar.foodRequest': 'Food Request Supplication',
                'azkar.guestBreakingFast': 'Guest Breaking Fast Supplication',
                'azkar.fastingPerson': 'Fasting Person Supplication',
                'azkar.fastingInsult': 'Fasting Insult Response',
                'azkar.firstFruit': 'First Fruit Supplication',
                'azkar.sneezing': 'Sneezing Supplication',
                'azkar.kafirSneezing': 'Kafir Sneezing Response',
                'azkar.marriage': 'Marriage Supplication',
                'azkar.marriageAndAnimal': 'Marriage and Animal Purchase Supplication',
                'azkar.beforeIntimacy': 'Before Intimacy Supplication',
                'azkar.anger': 'Anger Supplication',
                'azkar.afflictedPerson': 'Afflicted Person Supplication',
                'azkar.gathering': 'Gathering Supplication',
                'azkar.gatheringExpiation': 'Gathering Expiation',
                'azkar.forgivenessRequest': 'Forgiveness Request Supplication',
                'azkar.kindness': 'Kindness Supplication',
                'azkar.dajjalProtection': 'Dajjal Protection',
                'azkar.loveInAllah': 'Love in Allah Supplication',
                'azkar.wealthOffer': 'Wealth Offer Supplication',
                'azkar.loanRepayment': 'Loan Repayment Supplication',
                'azkar.shirkFear': 'Shirk Fear Supplication',
                'azkar.blessingResponse': 'Blessing Response Supplication',
                'azkar.badOmen': 'Bad Omen Supplication',
                'azkar.riding': 'Riding Supplication',
                'azkar.travel': 'Travel Supplication',
                'azkar.enteringVillage': 'Entering Village Supplication',
                'azkar.enteringMarket': 'Entering Market Supplication',
                'azkar.vehicleTrouble': 'Vehicle Trouble Supplication',
                'azkar.travelerForResident': 'Traveler for Resident Supplication',
                'azkar.residentForTraveler': 'Resident for Traveler Supplication',
                'azkar.travelTasbih': 'Travel Tasbih and Takbir',
                'azkar.travelerDawn': 'Traveler Dawn Supplication',
                'azkar.travelStop': 'Travel Stop Supplication',
                'azkar.returningFromTravel': 'Returning from Travel Remembrance',
                'azkar.goodOrBadNews': 'Good or Bad News Response',
                'azkar.blessingProphet': 'Blessing Prophet Virtue',
                'azkar.spreadingSalam': 'Spreading Salam',
                'azkar.kafirSalam': 'Kafir Salam Response',
                'azkar.roosterCrow': 'Rooster Crow Supplication',
                'azkar.dogBark': 'Dog Bark Supplication',
                'azkar.insulted': 'Insulted Supplication',
                'azkar.praise': 'Praise Response',
                'azkar.compliment': 'Compliment Response',
                'azkar.hajjTalbiyah': 'Hajj Talbiyah',
                'azkar.blackStoneTakbir': 'Black Stone Takbir',
                'azkar.yamaniCorner': 'Yamani Corner Supplication',
                'azkar.safaMarwa': 'Safa Marwa Supplication',
                'azkar.arafatDay': 'Arafat Day Supplication',
                'azkar.masharHaram': 'Mashar Haram Remembrance',
                'azkar.stoneThrowing': 'Stone Throwing Takbir',
                'azkar.amazement': 'Amazement Supplication',
                'azkar.goodNews': 'Good News Response',
                'azkar.bodyPain': 'Body Pain Supplication',
                'azkar.evilEye': 'Evil Eye Supplication',
                'azkar.fright': 'Fright Supplication',
                'azkar.slaughtering': 'Slaughtering Supplication',
                'azkar.satanRepellent2': 'Satan Repellent Supplication 2',
                'azkar.repentance': 'Repentance and Forgiveness',
                'azkar.tasbihVirtue': 'Tasbih and Praise Virtue',
                'azkar.prophetTasbih': 'Prophet\'s Tasbih Method',
                'azkar.goodDeeds': 'Good Deeds and Etiquette',
                'azkar.dhikrAdded': 'Dhikr added: {text} ({count} times)',
                'azkar.dhikrCompleted': 'Dhikr completed: {text}!',
                'azkar.dhikrLinked': 'Dhikr linked: {text} with tasbih',
                'azkar.counterReset': 'Counter reset',
                'azkar.dhikrLinkedWithTasbih': 'Dhikr linked with tasbih',
                
                // Radio Stations
                'radio.egyptQuran': 'Egypt Quran Radio – Cairo',
                'radio.tarateel': 'Tarateel',
                'radio.tlawat': 'Beautiful Recitations',
                'radio.tafsir': 'Tafsir',
                'radio.sira': 'Concise Biography of the Prophet',
                'radio.siraShadows': 'In the Shadows of the Prophet\'s Biography',
                'radio.sahaba': 'Pictures from the Lives of the Companions',
                'radio.abdulbasitMoratal': 'Sheikh Abdul Basit Abdul Samad – Eternal Recitations',
                'radio.abdulbasitMojawwad': 'Sheikh Abdul Basit Abdul Samad Radio',
                'radio.selectStation': 'Select Radio Station',
                'radio.fromList': 'From List',
                'radio.nowPlaying': 'Now Playing',
                'radio.volume': 'Volume',
                'radio.mute': 'Mute',
                'radio.unmute': 'Unmute',
                'radio.stop': 'Stop',
                'radio.play': 'Play',
                'radio.pause': 'Pause',
                'radio.loading': 'Loading...',
                'radio.error': 'Playback Error',
                'radio.retry': 'Retry',
                'radio.description': 'Listen to the best Islamic radio stations from various Arab countries',
                
                // Quran Readers
                'reader.alafasy': 'Mishary Alafasy',
                'reader.yasseraldossari': 'Yasser Al-Dosari',
                'reader.abdulbasitmurattal': 'Abdul Basit Abdul Samad (Murattal)',
                'reader.abdulbasitmujawwad': 'Abdul Basit Abdul Samad (Mujawwad)',
                'reader.ahmedalajmi': 'Ahmed Al-Ajmi',
                'reader.muhammadayyub': 'Muhammad Ayyub',
                'reader.abdulazizazzahrani': 'Abdul Aziz Al-Zahrani',
                'reader.muhammadsiddiqalminshawimujawwad': 'Muhammad Siddiq Al-Minshawi (Mujawwad)',
                'reader.mustafaismail': 'Mustafa Ismail',
                'reader.abdullahalmatrood': 'Abdullah Al-Matrood',
                'reader.abdullahawadaljuhani': 'Abdullah Awad Al-Juhani',
                'reader.abdullahbasfar': 'Abdullah Basfar',
                'reader.abdullahkhayat': 'Abdullah Khayat',
                'reader.abdullahkhulaifi': 'Abdullah Khulaifi',
                'reader.abdulmohsenalharthy': 'Abdul Mohsen Al-Harthy',
                'reader.abdulmuhsinalqasim': 'Abdul Muhsin Al-Qasim',
                'reader.abdulmunimabdulmubdi': 'Abdul Munim Abdul Mubdi',
                'reader.abdulwadoodhaneef': 'Abdul Wadood Haneef',
                'reader.abdurrasheedsufiabialhaarithanalkasaaee': 'Abdur Rashid Sufi [Abi Al-Harith from Al-Kasaaee]',
                'reader.abdurrasheedsufiaddoorianabiamr': 'Abdur Rashid Sufi [Ad-Doori from Abi Amr]',
                'reader.abdurrasheedsufishubahanasim': 'Abdur Rashid Sufi [Shu\'bah from Asim]',
                'reader.abdurrasheedsufisoosi': 'Abdur Rashid Sufi [As-Soosi]',
                'reader.abdurrazaqbinabtanaldulaimi': 'Abdur Razzaq bin Abtan Al-Dulaimi',
                'reader.abuabdullahmuniraltounsi': 'Abu Abdullah Munir Al-Tounsi',
                'reader.abubakraldhabi': 'Abu Bakr Al-Dhahabi',
                'reader.adilkalbani': 'Adil Kalbani',
                'reader.ahmadalhawashy': 'Ahmad Al-Hawashy',
                'reader.ahmadalnufais': 'Ahmad Al-Nufais',
                'reader.ahmadkhaderaltarabulsi': 'Ahmad Khader Al-Tarabulsi',
                'reader.ahmadsulaiman': 'Ahmad Sulaiman',
                'reader.ahmedalhammad': 'Ahmed Al-Hammad',
                'reader.ahmedalmisbahi': 'Ahmed Al-Misbahi',
                'reader.ahmedamir': 'Ahmed Amir',
                'reader.ahmedmohamedsalama': 'Ahmed Mohamed Salama',
                'reader.ahmedsaber': 'Ahmed Saber',
                'reader.alashryomran': 'Al-Ashry Omran',
                
                // Player
                'player.showMoreReaders': 'Show More Readers',
                'player.selectReader': 'Select Reader',
                'player.searchReader': 'Search for reader...',
                
                // Surah Names
                'surah.al-fatihah': 'Al-Fatihah',
                'surah.al-baqarah': 'Al-Baqarah',
                'surah.ali-imran': 'Ali \'Imran',
                'surah.an-nisa': 'An-Nisa',
                'surah.al-maidah': 'Al-Ma\'idah',
                'surah.al-anam': 'Al-An\'am',
                'surah.al-araf': 'Al-A\'raf',
                'surah.al-anfal': 'Al-Anfal',
                'surah.at-tawbah': 'At-Tawbah',
                'surah.yunus': 'Yunus',
                'surah.hud': 'Hud',
                'surah.yusuf': 'Yusuf',
                'surah.ar-rad': 'Ar-Ra\'d',
                'surah.ibrahim': 'Ibrahim',
                'surah.al-hijr': 'Al-Hijr',
                'surah.an-nahl': 'An-Nahl',
                'surah.al-isra': 'Al-Isra',
                'surah.al-kahf': 'Al-Kahf',
                'surah.maryam': 'Maryam',
                'surah.taha': 'Taha',
                'surah.al-anbiya': 'Al-Anbiya',
                'surah.al-hajj': 'Al-Hajj',
                'surah.al-muminun': 'Al-Mu\'minun',
                'surah.an-nur': 'An-Nur',
                'surah.al-furqan': 'Al-Furqan',
                'surah.ash-shuara': 'Ash-Shu\'ara',
                'surah.an-naml': 'An-Naml',
                'surah.al-qasas': 'Al-Qasas',
                'surah.al-ankabut': 'Al-\'Ankabut',
                'surah.ar-rum': 'Ar-Rum',
                'surah.luqman': 'Luqman',
                'surah.as-sajdah': 'As-Sajdah',
                'surah.al-ahzab': 'Al-Ahzab',
                'surah.saba': 'Saba',
                'surah.fatir': 'Fatir',
                'surah.ya-sin': 'Ya-Sin',
                'surah.as-saffat': 'As-Saffat',
                'surah.sad': 'Sad',
                'surah.az-zumar': 'Az-Zumar',
                'surah.ghafir': 'Ghafir',
                'surah.fussilat': 'Fussilat',
                'surah.ash-shura': 'Ash-Shura',
                'surah.az-zukhruf': 'Az-Zukhruf',
                'surah.ad-dukhan': 'Ad-Dukhan',
                'surah.al-jathiyah': 'Al-Jathiyah',
                'surah.al-ahqaf': 'Al-Ahqaf',
                'surah.muhammad': 'Muhammad',
                'surah.al-fath': 'Al-Fath',
                'surah.al-hujurat': 'Al-Hujurat',
                'surah.qaf': 'Qaf',
                'surah.adh-dhariyat': 'Adh-Dhariyat',
                'surah.at-tur': 'At-Tur',
                'surah.an-najm': 'An-Najm',
                'surah.al-qamar': 'Al-Qamar',
                'surah.ar-rahman': 'Ar-Rahman',
                'surah.al-waqiah': 'Al-Waqi\'ah',
                'surah.al-hadid': 'Al-Hadid',
                'surah.al-mujadila': 'Al-Mujadila',
                'surah.al-hashr': 'Al-Hashr',
                'surah.al-mumtahanah': 'Al-Mumtahanah',
                'surah.as-saff': 'As-Saff',
                'surah.al-jumuah': 'Al-Jumu\'ah',
                'surah.al-munafiqun': 'Al-Munafiqun',
                'surah.at-taghabun': 'At-Taghabun',
                'surah.at-talaq': 'At-Talaq',
                'surah.at-tahrim': 'At-Tahrim',
                'surah.al-mulk': 'Al-Mulk',
                'surah.al-qalam': 'Al-Qalam',
                'surah.al-haqqah': 'Al-Haqqah',
                'surah.al-maarij': 'Al-Ma\'arij',
                'surah.nuh': 'Nuh',
                'surah.al-jinn': 'Al-Jinn',
                'surah.al-muzzammil': 'Al-Muzzammil',
                'surah.al-muddaththir': 'Al-Muddaththir',
                'surah.al-qiyamah': 'Al-Qiyamah',
                'surah.al-insan': 'Al-Insan',
                'surah.al-mursalat': 'Al-Mursalat',
                'surah.an-naba': 'An-Naba',
                'surah.an-naziat': 'An-Naziat',
                'surah.abasa': 'Abasa',
                'surah.at-takwir': 'At-Takwir',
                'surah.al-infitar': 'Al-Infitar',
                'surah.al-mutaffifin': 'Al-Mutaffifin',
                'surah.al-inshiqaq': 'Al-Inshiqaq',
                'surah.al-buruj': 'Al-Buruj',
                'surah.at-tariq': 'At-Tariq',
                'surah.al-ala': 'Al-A\'la',
                'surah.al-ghashiyah': 'Al-Ghashiyah',
                'surah.al-fajr': 'Al-Fajr',
                'surah.al-balad': 'Al-Balad',
                'surah.ash-shams': 'Ash-Shams',
                'surah.al-layl': 'Al-Layl',
                'surah.ad-duha': 'Ad-Duha',
                'surah.ash-sharh': 'Ash-Sharh',
                'surah.at-tin': 'At-Tin',
                'surah.al-alaq': 'Al-Alaq',
                'surah.al-qadr': 'Al-Qadr',
                'surah.al-bayyinah': 'Al-Bayyinah',
                'surah.az-zalzalah': 'Az-Zalzalah',
                'surah.al-adiyat': 'Al-Adiyat',
                'surah.al-qariah': 'Al-Qariah',
                'surah.at-takathur': 'At-Takathur',
                'surah.al-asr': 'Al-Asr',
                'surah.al-humazah': 'Al-Humazah',
                'surah.al-fil': 'Al-Fil',
                'surah.quraysh': 'Quraysh',
                'surah.al-maun': 'Al-Ma\'un',
                'surah.al-kawthar': 'Al-Kawthar',
                'surah.al-kafirun': 'Al-Kafirun',
                'surah.an-nasr': 'An-Nasr',
                'surah.al-masad': 'Al-Masad',
                'surah.al-ikhlas': 'Al-Ikhlas',
                'surah.al-falaq': 'Al-Falaq',
                'surah.an-nas': 'An-Nas'
            }
        };
        
        this.init();
    }
    
    init() {
        this.applyLanguage();
        // Setup language switcher after DOM is loaded
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => {
                this.setupLanguageSwitcher();
            });
        } else {
            this.setupLanguageSwitcher();
        }
    }
    
    getTranslation(key) {
        return this.translations[this.currentLanguage][key] || key;
    }
    
    setLanguage(language) {
        if (this.translations[language]) {
            this.currentLanguage = language;
            localStorage.setItem('language', language);
            this.applyLanguage();
            this.updateDocumentDirection();
        }
    }
    
    applyLanguage() {
        // Update all elements with data-translate attribute
        document.querySelectorAll('[data-translate]').forEach(element => {
            const key = element.getAttribute('data-translate');
            const translation = this.getTranslation(key);
            
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translation;
            } else {
                element.textContent = translation;
            }
        });
        
        // Update title attributes
        document.querySelectorAll('[data-translate-title]').forEach(element => {
            const key = element.getAttribute('data-translate-title');
            element.title = this.getTranslation(key);
        });
        
        // Update aria-label attributes
        document.querySelectorAll('[data-translate-aria]').forEach(element => {
            const key = element.getAttribute('data-translate-aria');
            element.setAttribute('aria-label', this.getTranslation(key));
        });
    }
    
    updateDocumentDirection() {
        const isRTL = this.currentLanguage === 'ar';
        document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
        document.documentElement.setAttribute('lang', this.currentLanguage);
        
        // Update body class for RTL/LTR specific styling
        document.body.classList.remove('rtl', 'ltr');
        document.body.classList.add(isRTL ? 'rtl' : 'ltr');
    }
    
    setupLanguageSwitcher() {
        // Create language switcher if it doesn't exist
        if (!document.getElementById('languageSwitcher')) {
            this.createLanguageSwitcher();
        }
    }
    
    createLanguageSwitcher() {
        const switcher = document.createElement('div');
        switcher.id = 'languageSwitcher';
        switcher.className = 'language-switcher';
        switcher.innerHTML = `
            <button class="language-btn" onclick="languageManager.toggleLanguage()">
                <i class="bi bi-translate"></i>
                <span data-translate="common.language">${this.currentLanguage === 'ar' ? 'English' : 'العربية'}</span>
            </button>
        `;
        
        // Add to sidebar
        const sidebar = document.getElementById('sidebar');
        if (sidebar) {
            const sidebarContent = sidebar.querySelector('.sidebar-content .nav-section');
            if (sidebarContent) {
                // Insert before the close button
                const closeBtn = sidebarContent.querySelector('button[onclick="toggleSidebar()"]');
                if (closeBtn) {
                    sidebarContent.insertBefore(switcher, closeBtn);
                } else {
                    sidebarContent.appendChild(switcher);
                }
            }
        }
    }
    
    toggleLanguage() {
        const newLanguage = this.currentLanguage === 'ar' ? 'en' : 'ar';
        this.setLanguage(newLanguage);
        
        // Update the switcher button text
        const switcherSpan = document.querySelector('#languageSwitcher span');
        if (switcherSpan) {
            switcherSpan.textContent = newLanguage === 'ar' ? 'English' : 'العربية';
        }
    }
    
    // Method to get current language
    getCurrentLanguage() {
        return this.currentLanguage;
    }
    
    // Method to check if current language is RTL
    isRTL() {
        return this.currentLanguage === 'ar';
    }
    
    // Method to get translated radio station name
    getRadioStationName(stationId) {
        const stationNames = {
            'egypt-quran': 'radio.egyptQuran',
            'tarateel': 'radio.tarateel',
            'tlawat': 'radio.tlawat',
            'mukhtasartafsir': 'radio.tafsir',
            'almukhtasar_fi_alsiyra': 'radio.sira',
            'fi_zilal_alsiyra': 'radio.siraShadows',
            'sahaba-radio': 'radio.sahaba',
            'abdulbasit_abdulsamad_moratal': 'radio.abdulbasitMoratal',
            'abdulbasit_abdulsamad_mojawwad': 'radio.abdulbasitMojawwad'
        };
        
        const translationKey = stationNames[stationId];
        return translationKey ? this.getTranslation(translationKey) : stationId;
    }
    
    // Method to get translated azkar category
    getAzkarCategoryName(category) {
        const categoryNames = {
            'أذكار الصباح والمساء': 'azkar.morningEvening',
            'أذكار النوم': 'azkar.sleeping',
            'أذكار الاستيقاظ من النوم': 'azkar.waking',
            'دعاء دخول الخلاء': 'azkar.toiletEnter',
            'دعاء الخروج من الخلاء': 'azkar.toiletExit',
            'الذكر قبل الوضوء': 'azkar.beforeWudu',
            'الذكر بعد الفراغ من الوضوء': 'azkar.afterWudu',
            'الذكر عند الخروج من المنزل': 'azkar.leavingHome',
            'الذكر عند دخول المنزل': 'azkar.enteringHome',
            'دعاء الذهاب إلى المسجد': 'azkar.goingToMosque',
            'دعاء دخول المسجد': 'azkar.enteringMosque',
            'دعاء الخروج من المسجد': 'azkar.leavingMosque',
            'أذكار الآذان': 'azkar.adhan',
            'دعاء لبس الثوب': 'azkar.wearingClothes',
            'دعاء لبس الثوب الجديد': 'azkar.wearingNewClothes',
            'الدعاء لمن لبس ثوبا جديدا': 'azkar.blessingNewClothes',
            'ما يقول إذا وضع ثوبه': 'azkar.removingClothes',
            'دعاء الاستفتاح': 'azkar.openingPrayer',
            'دعاء الركوع': 'azkar.ruku',
            'دعاء الرفع من الركوع': 'azkar.risingFromRuku',
            'دعاء السجود': 'azkar.sujood',
            'دعاء الجلسة بين السجدتين': 'azkar.sittingBetweenSujood',
            'دعاء سجود التلاوة': 'azkar.sujoodTilawah',
            'التشهد': 'azkar.tashahhud',
            'الصلاة على النبي بعد التشهد': 'azkar.sendingBlessings',
            'الدعاء بعد التشهد الأخير قبل السلام': 'azkar.finalSupplication',
            'الأذكار بعد السلام من الصلاة': 'azkar.afterPrayer',
            'دعاء صلاة الاستخارة': 'azkar.istikharah',
            'الدعاء إذا تقلب ليلا': 'azkar.nightTurning',
            'دعاء الفزع في النوم و من بُلِيَ بالوحشة': 'azkar.nightmare',
            'ما يفعل من رأى الرؤيا أو الحلم': 'azkar.dreams',
            'دعاء قنوت الوتر': 'azkar.witrQunoot',
            'الذكر عقب السلام من الوتر': 'azkar.afterWitr',
            'دعاء الهم والحزن': 'azkar.sadness',
            'دعاء الكرب': 'azkar.distress',
            'دعاء لقاء العدو و ذي السلطان': 'azkar.enemyMeeting',
            'دعاء من خاف ظلم السلطان': 'azkar.oppressionFear',
            'الدعاء على العدو': 'azkar.againstEnemy',
            'ما يقول من خاف قوما': 'azkar.peopleFear',
            'دعاء من أصابه وسوسة في الإيمان': 'azkar.faithDoubt',
            'دعاء قضاء الدين': 'azkar.debtRepayment',
            'دعاء الوسوسة في الصلاة و القراءة': 'azkar.prayerWhisper',
            'دعاء من استصعب عليه أمر': 'azkar.difficultMatter',
            'ما يقول ويفعل من أذنب ذنبا': 'azkar.sinCommitted',
            'دعاء طرد الشيطان و وساوسه': 'azkar.satanRepellent',
            'الدعاء حينما يقع ما لا يرضاه أو غلب على أمره': 'azkar.unwantedEvent',
            'تهنئة المولود له وجوابه': 'azkar.newbornCongratulation',
            'ما يعوذ به الأولاد': 'azkar.childrenProtection',
            'الدعاء للمريض في عيادته': 'azkar.visitingSick',
            'فضل عيادة المريض': 'azkar.visitingSickVirtue',
            'دعاء المريض الذي يئس من حياته': 'azkar.dyingPerson',
            'تلقين المحتضر': 'azkar.deathbed',
            'دعاء من أصيب بمصيبة': 'azkar.calamity',
            'الدعاء عند إغماض الميت': 'azkar.closingEyes',
            'الدعاء للميت في الصلاة عليه': 'azkar.deadPersonPrayer',
            'الدعاء للفرط في الصلاة عليه': 'azkar.childPrayer',
            'دعاء التعزية': 'azkar.condolence',
            'الدعاء عند إدخال الميت القبر': 'azkar.burial',
            'الدعاء بعد دفن الميت': 'azkar.afterBurial',
            'دعاء زيارة القبور': 'azkar.graveVisiting',
            'دعاء الريح': 'azkar.wind',
            'دعاء الرعد': 'azkar.thunder',
            'من أدعية الاستسقاء': 'azkar.rainRequest',
            'الدعاء إذا نزل المطر': 'azkar.rainFalling',
            'الذكر بعد نزول المطر': 'azkar.afterRain',
            'من أدعية الاستصحاء': 'azkar.sunshineRequest',
            'دعاء رؤية الهلال': 'azkar.newMoon',
            'الدعاء عند إفطار الصائم': 'azkar.breakingFast',
            'الدعاء قبل الطعام': 'azkar.beforeEating',
            'الدعاء عند الفراغ من الطعام': 'azkar.afterEating',
            'دعاء الضيف لصاحب الطعام': 'azkar.guestBlessing',
            'التعريض بالدعاء لطلب الطعام أو الشراب': 'azkar.foodRequest',
            'الدعاء إذا أفطر عند أهل بيت': 'azkar.guestBreakingFast',
            'دعاء الصائم إذا حضر الطعام ولم يفطر': 'azkar.fastingPerson',
            'ما يقول الصائم إذا سابه أحد': 'azkar.fastingInsult',
            'الدعاء عند رؤية باكورة الثمر': 'azkar.firstFruit',
            'دعاء العطاس': 'azkar.sneezing',
            'ما يقال للكافر إذا عطس فحمد الله': 'azkar.kafirSneezing',
            'الدعاء للمتزوج': 'azkar.marriage',
            'دعاء المتزوج و شراء الدابة': 'azkar.marriageAndAnimal',
            'الدعاء قبل إتيان الزوجة': 'azkar.beforeIntimacy',
            'دعاء الغضب': 'azkar.anger',
            'دعاء من رأى مبتلى': 'azkar.afflictedPerson',
            'ما يقال في المجلس': 'azkar.gathering',
            'كفارة المجلس': 'azkar.gatheringExpiation',
            'الدعاء لمن قال غفر الله لك': 'azkar.forgivenessRequest',
            'الدعاء لمن صنع إليك معروفا': 'azkar.kindness',
            'ما يعصم الله به من الدجال': 'azkar.dajjalProtection',
            'الدعاء لمن قال إني أحبك في الله': 'azkar.loveInAllah',
            'الدعاء لمن عرض عليك ماله': 'azkar.wealthOffer',
            'الدعاء لمن أقرض عند القضاء': 'azkar.loanRepayment',
            'دعاء الخوف من الشرك': 'azkar.shirkFear',
            'الدعاء لمن قال بارك الله فيك': 'azkar.blessingResponse',
            'دعاء كراهية الطيرة': 'azkar.badOmen',
            'دعاء الركوب': 'azkar.riding',
            'دعاء السفر': 'azkar.travel',
            'دعاء دخول القرية أو البلدة': 'azkar.enteringVillage',
            'دعاء دخول السوق': 'azkar.enteringMarket',
            'الدعاء إذا تعس المركوب': 'azkar.vehicleTrouble',
            'دعاء المسافر للمقيم': 'azkar.travelerForResident',
            'دعاء المقيم للمسافر': 'azkar.residentForTraveler',
            'التكبير و التسبيح في سير السفر': 'azkar.travelTasbih',
            'دعاء المسافر إذا أسحر': 'azkar.travelerDawn',
            'الدعاء إذا نزل مترلا في سفر أو غيره': 'azkar.travelStop',
            'ذكر الرجوع من السفر': 'azkar.returningFromTravel',
            'ما يقول من أتاه أمر يسره أو يكرهه': 'azkar.goodOrBadNews',
            'فضل الصلاة على النبي صلى الله عليه و سلم': 'azkar.blessingProphet',
            'إفشاء السلام': 'azkar.spreadingSalam',
            'كيف يرد السلام على الكافر إذا سلم': 'azkar.kafirSalam',
            'الدُّعاءُ عِنْدَ سَمَاعِ صِياحِ الدِّيكِ ونَهِيقِ الْحِمَارِ': 'azkar.roosterCrow',
            'دعاء نباح الكلاب بالليل': 'azkar.dogBark',
            'الدعاء لمن سببته': 'azkar.insulted',
            'ما يقول المسلم إذا مدح المسلم': 'azkar.praise',
            'ما يقول المسلم إذا زكي': 'azkar.compliment',
            'كيف يلبي المحرم في الحج أو العمرة ؟': 'azkar.hajjTalbiyah',
            'التكبير إذا أتى الركن الأسود': 'azkar.blackStoneTakbir',
            'الدعاء بين الركن اليماني والحجر الأسود': 'azkar.yamaniCorner',
            'دعاء الوقوف على الصفا والمروة': 'azkar.safaMarwa',
            'الدعاء يوم عرفة': 'azkar.arafatDay',
            'الذكر عند المشعر الحرام': 'azkar.masharHaram',
            'التكبير عند رمي الجمار مع كل حصاة': 'azkar.stoneThrowing',
            'دعاء التعجب والأمر السار': 'azkar.amazement',
            'ما يفعل من أتاه أمر يسره': 'azkar.goodNews',
            'ما يقول من أحس وجعا في جسده': 'azkar.bodyPain',
            'دعاء من خشي أن يصيب شيئا بعينه': 'azkar.evilEye',
            'ما يقال عند الفزع': 'azkar.fright',
            'ما يقول عند الذبح أو النحر': 'azkar.slaughtering',
            'ما يقول لرد كيد مردة الشياطين': 'azkar.satanRepellent2',
            'الاستغفار و التوبة': 'azkar.repentance',
            'فضل التسبيح و التحميد، و التهليل، و التكبير': 'azkar.tasbihVirtue',
            'كيف كان النبي يسبح؟': 'azkar.prophetTasbih',
            'من أنواع الخير والآداب الجامعة': 'azkar.goodDeeds'
        };
        
        const translationKey = categoryNames[category];
        return translationKey ? this.getTranslation(translationKey) : category;
    }
    
    // Method to get translated Quran reader name
    getQuranReaderName(readerValue) {
        const readerNames = {
            'ar.alafasy': 'reader.alafasy',
            'ar.yasseraldossari': 'reader.yasseraldossari',
            'ar.abdulbasitmurattal': 'reader.abdulbasitmurattal',
            'ar.abdulbasitmujawwad': 'reader.abdulbasitmujawwad',
            'ar.ahmedalajmi': 'reader.ahmedalajmi',
            'ar.muhammadayyub': 'reader.muhammadayyub',
            'ar.abdulazizazzahrani': 'reader.abdulazizazzahrani',
            'ar.muhammadsiddiqalminshawimujawwad': 'reader.muhammadsiddiqalminshawimujawwad',
            'ar.mustafaismail': 'reader.mustafaismail',
            'ar.abdullahalmatrood': 'reader.abdullahalmatrood',
            'ar.abdullahawadaljuhani': 'reader.abdullahawadaljuhani',
            'ar.abdullahbasfar': 'reader.abdullahbasfar',
            'ar.abdullahkhayat': 'reader.abdullahkhayat',
            'ar.abdullahkhulaifi': 'reader.abdullahkhulaifi',
            'ar.abdulmohsenalharthy': 'reader.abdulmohsenalharthy',
            'ar.abdulmuhsinalqasim': 'reader.abdulmuhsinalqasim',
            'ar.abdulmunimabdulmubdi': 'reader.abdulmunimabdulmubdi',
            'ar.abdulwadoodhaneef': 'reader.abdulwadoodhaneef',
            'ar.abdurrasheedsufiabialhaarithanalkasaaee': 'reader.abdurrasheedsufiabialhaarithanalkasaaee',
            'ar.abdurrasheedsufiaddoorianabiamr': 'reader.abdurrasheedsufiaddoorianabiamr',
            'ar.abdurrasheedsufishubahanasim': 'reader.abdurrasheedsufishubahanasim',
            'ar.abdurrasheedsufisoosi': 'reader.abdurrasheedsufisoosi',
            'ar.abdurrazaqbinabtanaldulaimi': 'reader.abdurrazaqbinabtanaldulaimi',
            'ar.abuabdullahmuniraltounsi': 'reader.abuabdullahmuniraltounsi',
            'ar.abubakraldhabi': 'reader.abubakraldhabi',
            'ar.adilkalbani': 'reader.adilkalbani',
            'ar.ahmadalhawashy': 'reader.ahmadalhawashy',
            'ar.ahmadalnufais': 'reader.ahmadalnufais',
            'ar.ahmadkhaderaltarabulsi': 'reader.ahmadkhaderaltarabulsi',
            'ar.ahmadsulaiman': 'reader.ahmadsulaiman',
            'ar.ahmedalhammad': 'reader.ahmedalhammad',
            'ar.ahmedalmisbahi': 'reader.ahmedalmisbahi',
            'ar.ahmedamir': 'reader.ahmedamir',
            'ar.ahmedmohamedsalama': 'reader.ahmedmohamedsalama',
            'ar.ahmedsaber': 'reader.ahmedsaber',
            'ar.alashryomran': 'reader.alashryomran'
        };
        
        const translationKey = readerNames[readerValue];
        return translationKey ? this.getTranslation(translationKey) : readerValue;
    }
    
    // Method to get translated surah name
    getSurahName(surahNumber) {
        const surahKeys = {
            1: 'surah.al-fatihah',
            2: 'surah.al-baqarah',
            3: 'surah.ali-imran',
            4: 'surah.an-nisa',
            5: 'surah.al-maidah',
            6: 'surah.al-anam',
            7: 'surah.al-araf',
            8: 'surah.al-anfal',
            9: 'surah.at-tawbah',
            10: 'surah.yunus',
            11: 'surah.hud',
            12: 'surah.yusuf',
            13: 'surah.ar-rad',
            14: 'surah.ibrahim',
            15: 'surah.al-hijr',
            16: 'surah.an-nahl',
            17: 'surah.al-isra',
            18: 'surah.al-kahf',
            19: 'surah.maryam',
            20: 'surah.taha',
            21: 'surah.al-anbiya',
            22: 'surah.al-hajj',
            23: 'surah.al-muminun',
            24: 'surah.an-nur',
            25: 'surah.al-furqan',
            26: 'surah.ash-shuara',
            27: 'surah.an-naml',
            28: 'surah.al-qasas',
            29: 'surah.al-ankabut',
            30: 'surah.ar-rum',
            31: 'surah.luqman',
            32: 'surah.as-sajdah',
            33: 'surah.al-ahzab',
            34: 'surah.saba',
            35: 'surah.fatir',
            36: 'surah.ya-sin',
            37: 'surah.as-saffat',
            38: 'surah.sad',
            39: 'surah.az-zumar',
            40: 'surah.ghafir',
            41: 'surah.fussilat',
            42: 'surah.ash-shura',
            43: 'surah.az-zukhruf',
            44: 'surah.ad-dukhan',
            45: 'surah.al-jathiyah',
            46: 'surah.al-ahqaf',
            47: 'surah.muhammad',
            48: 'surah.al-fath',
            49: 'surah.al-hujurat',
            50: 'surah.qaf',
            51: 'surah.adh-dhariyat',
            52: 'surah.at-tur',
            53: 'surah.an-najm',
            54: 'surah.al-qamar',
            55: 'surah.ar-rahman',
            56: 'surah.al-waqiah',
            57: 'surah.al-hadid',
            58: 'surah.al-mujadila',
            59: 'surah.al-hashr',
            60: 'surah.al-mumtahanah',
            61: 'surah.as-saff',
            62: 'surah.al-jumuah',
            63: 'surah.al-munafiqun',
            64: 'surah.at-taghabun',
            65: 'surah.at-talaq',
            66: 'surah.at-tahrim',
            67: 'surah.al-mulk',
            68: 'surah.al-qalam',
            69: 'surah.al-haqqah',
            70: 'surah.al-maarij',
            71: 'surah.nuh',
            72: 'surah.al-jinn',
            73: 'surah.al-muzzammil',
            74: 'surah.al-muddaththir',
            75: 'surah.al-qiyamah',
            76: 'surah.al-insan',
            77: 'surah.al-mursalat',
            78: 'surah.an-naba',
            79: 'surah.an-naziat',
            80: 'surah.abasa',
            81: 'surah.at-takwir',
            82: 'surah.al-infitar',
            83: 'surah.al-mutaffifin',
            84: 'surah.al-inshiqaq',
            85: 'surah.al-buruj',
            86: 'surah.at-tariq',
            87: 'surah.al-ala',
            88: 'surah.al-ghashiyah',
            89: 'surah.al-fajr',
            90: 'surah.al-balad',
            91: 'surah.ash-shams',
            92: 'surah.al-layl',
            93: 'surah.ad-duha',
            94: 'surah.ash-sharh',
            95: 'surah.at-tin',
            96: 'surah.al-alaq',
            97: 'surah.al-qadr',
            98: 'surah.al-bayyinah',
            99: 'surah.az-zalzalah',
            100: 'surah.al-adiyat',
            101: 'surah.al-qariah',
            102: 'surah.at-takathur',
            103: 'surah.al-asr',
            104: 'surah.al-humazah',
            105: 'surah.al-fil',
            106: 'surah.quraysh',
            107: 'surah.al-maun',
            108: 'surah.al-kawthar',
            109: 'surah.al-kafirun',
            110: 'surah.an-nasr',
            111: 'surah.al-masad',
            112: 'surah.al-ikhlas',
            113: 'surah.al-falaq',
            114: 'surah.an-nas'
        };
        
        const translationKey = surahKeys[surahNumber];
        return translationKey ? this.getTranslation(translationKey) : `Surah ${surahNumber}`;
    }
}

// Initialize language manager
const languageManager = new LanguageManager();
